# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nde_playground',
                'doc_host': 'https://UpstatePedro.github.io',
                'git_url': 'https://github.com/UpstatePedro/nde_playground',
                'lib_path': 'nde_playground'},
  'syms': {'nde_playground.core': {'nde_playground.core.foo': ('core.html#foo', 'nde_playground/core.py')}}}
